title: GitHubPagesデモサイト
author: Yusuke Soraji

theme: minima
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

plugins:
  - jekyll-feed
  - jekyll-titles-from-headings

titles_from_headings:
  strip_title: true
  collections: false

# ヘッダーメニューに表示するページの設定
header_pages:
  - about-system.md
  - setup.md
  - commonmark-guide.md
  - page-management.md
  - posts.md
  - file-management.md
  - update-operations.md
  - templates.md
  - configuration.md
  - minima-customization.md
  - troubleshooting.md